'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Otvets',
      [
        {
          voprosId: 1,
          name: 'Толя',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 1,
          name: 'Юра',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 1,
          name: 'Влад',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 2,
          name: 'Boch',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 2,
          name: 'Atlant',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 2,
          name: 'LG',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 3,
          name: 'niedźwiedź (медведь)',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 3,
          name: 'bawół (буйвол)',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 3,
          name: 'bóbr',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 4,
          name: '5',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 4,
          name: 'Все',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 4,
          name: '!(!("Все"))',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 5,
          name: 'Южным',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 5,
          name: 'Региональным',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 5,
          name: 'Муууучительным',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 6,
          name: 'Дисней',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 6,
          name: 'Эльбрус',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 6,
          name: 'Анатолий когда собрался на рыбалку',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 7,
          name: 'Класть',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 7,
          name: 'Ложить',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 7,
          name: 'Положить?',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 8,
          name: 'Их трудно подбирать',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 8,
          name: 'Слово не воробей, в лес не убежит',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 8,
          name: 'За них нужно отвечать',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 9,
          name: 'Их можно есть в пост',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 9,
          name: 'Строят плотины',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 9,
          name: 'Едят деревья',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 10,
          name: 'Код ревью',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 10,
          name: 'Входную дверь',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 10,
          name: 'Пятничные проекты',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 11,
          name: 'Одноклассником',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 11,
          name: 'Кентом',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 11,
          name: 'Женихом',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 12,
          name: 'Батэ',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 12,
          name: 'ТТ',
          isRight: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          voprosId: 12,
          name: 'Кумитэ',
          isRight: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Otvets', null, {});
  },
};
